[package]
name = "rs"
version = "0.6.9"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.58", features = ["derive"] }
tracing = "0.1"
tracing-core = "0.1.36"
tracing-glog = "0.4"
tracing-subscriber = "0.3.22"
